### ISSUE TITLE
Conda package can't be built conda-forge docker image

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#10]
The conda forge docker image uses GCC 4.8.
However, this version is not supported by the json library (see this issue https://github.com/nlohmann/json/pull/212).
The packages on my channel are built on my machine with GCC 5.4.0.
If you need support for an older GCC version (ABI issues), please built the package yourself with GCC 4.9 (which is supported).

**Comment by constantinpape** [comment]
I have circumvented this by disabling the compiler checks in the json library on my own fork.
This is fine for now because we dont depend on any features affected, however in the long run it would be better to switch to a json library that supports GCC 4.8.

**Comment by constantinpape** [comment]
Fixed by installing gcc 5 on the docker image, see
https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2

Can switch back to the main json repository again.
(Close this issue once this is done.)

**Comment by chaubold** [comment]
FYI: I tried building on the conda docker image as well but was bold and tried GCC 7. It builds successfully, but when I have another package with pybind11 (but in C++11 mode!) imported in my python session, importing z5py segfaults immediately. I assume that's because of some pybind11 symbols being conflicted...

**Comment by constantinpape** [comment]
Changed back to main json repository in 476bf65cb4477c5d10793b0abef1e4265fd05e31 .
@chaubold not sure about the gcc 7 issues, I will reopen this in a different issue when it becomes relevant again.
