### ISSUE TITLE
Parallel reads

### ISSUE THREAD

**Issue by unidesigner** [constantinpape/z5#116]
Just perhaps a simple question: Using Python, how is it possible to configure the number of threads to use when reading a larger array into memory from an N5 file? Thanks.

**Comment by constantinpape** [comment]
Very simple, you just need to set `n_threads` of the dataset to the desired number of threads:
```py
f = z5py.FIle('some_path')
ds = f['some_key']
ds.n_threads = 8
data = ds[:]  # this will read in parallel.
```
Note that this will also parallelize write operations.

**Comment by unidesigner** [comment]
Perfect, thanks!
