### ISSUE TITLE
Dataset cannot be passed to numpy.asarray

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#120]
When passed to `np.asarray`, a `Dataset` fails with the following traceback:
```
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/napari/layers/pyramid/pyramid.py", line 99, in __init__                                                    
    np.array([np.asarray(pyramid[-1])]), *args, **kwargs                                                                                                                                                    
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/numpy/core/_asarray.py", line 85, in asarray                                                               
    return array(a, dtype, copy=False, order=order)                                                                                                                                                         
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/z5py/dataset.py", line 430, in __getitem__                                                                 
    roi_begin, shape, to_squeeze = self.index_to_roi(index)                                                                                                                                                 
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/z5py/dataset.py", line 419, in index_to_roi                                                                
    normalized, to_squeeze = normalize_slices(index, self.shape)                                                                                                                                            
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/z5py/shape_utils.py", line 164, in normalize_slices                                                        
    normalized.append(int_to_start_stop(int(item), shape[d]))                                                                                                                                               
  File "/home/pape/Work/software/conda/miniconda3/envs/cluster_env37/lib/python3.7/site-packages/z5py/shape_utils.py", line 40, in int_to_start_stop                                                        
    raise ValueError('Index ({}) out of range (0-{})'.format(i, size - 1))                                                                                                                                  
ValueError: Index (63) out of range (0-62)              
```
The issue seems to be that a slice with stop `shape[0] +1` is requested, but `z5py` only supports up to `shape[0]`.

Would be good to investigate this further and fix it, because many downstream applications call `np.asarray` (or `np.array`) on passed arguments in places where we want to be able to pass a `z5py.Dataset`. For examle, I stumbled upon this issue when trying to pass one to [`napari.add_pyramid`](https://github.com/napari/napari/blob/0554c39f8ec97344d2b993949bf66674ba7485e8/napari/components/viewer_model.py#L373).

**Comment by clbarnes** [comment]
Although I haven't exercised it all that much, I haven't come across this issue in the other implementation I did of generic array slicing;https://github.com/clbarnes/h5py_like/blob/master/h5py_like/shape_utils.py . I have been meaning to see how much of that could be ported across to z5py without having to rebase everything on the `h5py_like` abstract base classes.

**Comment by jakirkham** [comment]
Interesting. Are you implementing [Python's buffer protocol]( https://docs.python.org/3/c-api/buffer.html )?

**Comment by constantinpape** [comment]
@clbarnes 
> I have been meaning to see how much of that could be ported across to z5py without having to rebase everything on the `h5py_like` abstract base classes.

That would be very interesting to see indeed. I will try to have a closer look at `h5py_like` soon, but I am not sure if I will have time to do so this week.

@jakirkham 
> Interesting. Are you implementing [Python's buffer protocol](https://docs.python.org/3/c-api/buffer.html)?

Is this prerequisite for `np.asarray` to work?

**Comment by jakirkham** [comment]
There are a bunch of ways one can make that work. The buffer protocol is handy and efficient if the data is already accessible via a pointer. If not, implementing [the `__array__` method]( https://docs.scipy.org/doc/numpy/reference/arrays.classes.html#numpy.class.__array__ ) could be a reasonable alternative.

**Comment by clbarnes** [comment]
> implementing the __array__ method

Would this simply be a case of 

```python
def __array__(self, dtype=None):
    arr = self[:]
    if dtype != self.dtype:
        arr = np.asarray(arr, dtype)
    return arr
```
?

**Comment by clbarnes** [comment]
I think once py2 (and maybe py35) is dropped #122 , most of `h5py_like.shape_utils` can pretty much be copied across. The `Indexer` class and the helper functions it relies on can go straight in, and then the `_getitem` and `_setitem` helpers from `IndexableArrayLike` can just be made into free functions or dropped into the existing `z5py.Dataset`.

**Comment by constantinpape** [comment]
> I think once py2 (and maybe py35)

Yes, I think we should drop 35 as well.

**Comment by constantinpape** [comment]
This is fixed now, see https://github.com/constantinpape/z5/blob/master/src/python/module/z5py/dataset.py#L54.
