### ISSUE TITLE
Axis order issues in the Python bindings?

### ISSUE THREAD

**Issue by stuarteberg** [constantinpape/z5#14]
There still seems to be some axis order issue in the Python bindings, or perhaps I'm doing something wrong.

I built `z5py` using today's latest commit (35c64f38557213cbff538b433347134e9e1c5936). (I updated the boost version in my build, but I doubt that matters.)

Setup:

```python
In [1]: import z5py

In [2]: import numpy as np

In [3]: f = z5py.File('/tmp/test.z5', use_zarr_format=False)

In [4]: ds = f.create_dataset('data', dtype='uint8', shape=(256,256,256),
   ...:                       chunks=(64,64,64), compressor='raw')
Out[4]: <z5py.dataset.Dataset at 0x104806390>
```

Write some random data:

```python
In [5]: data = np.random.randint(0,100, size=(256,256,256), dtype=np.uint8)

In [6]: ds[:] = data
```

If we read it back immediately, does it match what we wrote?

```python
In [7]: (data == ds[:]).all()
Out[7]: False
```

Bummer.  What about the first block only?

```python
In [8]: (ds[:64,:64,:64] == data[:64,:64,:64]).all()
Out[8]: False
```

Still no.  Is it an axis order issue? Try transposing.

```python
In [9]: (ds[:64,:64,:64].transpose() == data[:64,:64,:64]).all()
Out[9]: True
```

Ah-ha!  What if I transpose the whole volume?

```python
In [10]: (ds[:].transpose() == data).all()
Out[10]: False
```

Bummer. 😿

**Comment by constantinpape** [comment]
I have fixed the issue here:
https://github.com/constantinpape/z5/tree/debugn5_wip

to be precise, this commit:
https://github.com/constantinpape/z5/commit/df23f4f72c331c376de2d34b0f8a66b4423581cb


Note however, that this only works with the python bindings, I wasn't able to fix the underlying c++ backend yet. For your use case, this should be fine though.

**Comment by constantinpape** [comment]
All issues should be resolved with
https://github.com/constantinpape/z5/commit/79617668707804dc3bc2c33e9bfc58b6ed5cddc3

I am closing this, let me know if you still experience any issues.
