### ISSUE TITLE
How to know an attribute's type

### ISSUE THREAD

**Issue by halehawk** [constantinpape/z5#142]
If I have a z5 file, and I don't know any info about the file. When I read its json file which includes some info that are additional to all reserved key values, how can I get the type of the values in the json file? I tried to use typeid(jOut[key]).name(), it gave a very long string which includes more information than I expected.

**Comment by constantinpape** [comment]
z5 uses [nlohmann::json](https://github.com/nlohmann/json/) as json interface in c++.
The means that `jOut[key]`is probably a `nlohmann::json::value_t`, unless you cast it to another type.

You can use the `.type()` function to get the `value_t`, [see docs](https://nlohmann.github.io/json/classnlohmann_1_1basic__json_a2b2d781d7f2a4ee41bc0016e931cadf7.html).
From there on, you probably need to parse the return value yourself.

**Comment by halehawk** [comment]
Yes, I got the type from jOut[key].type(). jOut[key].type_name() can get me
the type as string.
Thanks a lot.

**Comment by constantinpape** [comment]
> Yes, I got the type from jOut[key].type(). jOut[key].type_name() can get me the type as string. Thanks a lot.

You're welcome ;). Closing this for now, let me know if there's any other issues.
