### ISSUE TITLE
If a variable has all value as zero

### ISSUE THREAD

**Issue by halehawk** [constantinpape/z5#143]
When I tried to write out data that has all value zero from z5 writesubarray, no data writes out at all. Is it a feature in z5?

**Comment by clbarnes** [comment]
The N5 filesystem format is sparse: only chunks with nonzero values in them should exist on the disk. Zeroing out chunks which do exist should delete those chunk files.

If the subarray being written is all zeros:

- chunk files completely contained in the subarray should be deleted
- chunk files with nonzero values which intersect with the subarray should be updated
- chunks with only zeros in them (i.e. chunk files which don't exist) shouldn't change

**Comment by halehawk** [comment]
On Thu, Nov 14, 2019 at 10:50 AM Chris Barnes <notifications@github.com>
wrote:

> The N5 filesystem format is sparse: only chunks with nonzero values in
> them should exist on the disk. Zeroing out chunks which do exist should
> delete those chunk files.
>
> If the subarray being written is all zeros:
>
>    - chunk files completely contained in the subarray should be deleted
>    - chunk files with nonzero values which intersect with the subarray
>    should be updated
>    - chunks with only zeros in them (i.e. chunk files which don't exist)
>    shouldn't change
>
> For the third one, chunks with only zeros in them shouldn't change, does
it mean shouldn't exist?

**Comment by constantinpape** [comment]
> it mean shouldn't exist?

Yes, it means chunks which are all zero should not be stored on disc and the library knows to load non-existing chunks as all zeros. 

Side-note: the zarr format supports setting the fillvalue as a parameter, it's zero by default.
If another fillvalue is set, empty chunks will be loaded with that fillvalue.
In n5, the fillvalue is hard-coded to zero.

**Comment by halehawk** [comment]
On Thu, Nov 14, 2019 at 4:06 PM Constantin Pape
<notifications@github.com> wrote:
>
> it mean shouldn't exist?
>
> Yes, it means chunks which are all zero should not be stored on disc and the library knows to load non-existing chunks as all zeros.
Do you mean if user wants to access non-existing chunks, they should
be able to get all zeros? I got failures instead.

**Comment by halehawk** [comment]
On Thu, Nov 14, 2019 at 4:17 PM Haiying Xu <haiyingx@ucar.edu> wrote:
>
> On Thu, Nov 14, 2019 at 4:06 PM Constantin Pape
> <notifications@github.com> wrote:
> >
> > it mean shouldn't exist?
> >
> > Yes, it means chunks which are all zero should not be stored on disc and the library knows to load non-existing chunks as all zeros.
> Do you mean if user wants to access non-existing chunks, they should
> be able to get all zeros? I got failures instead.
Maybe I have something wrong here, I will test to access those
non-existing chunks.

Just another issue is that how I can save a variable that has no
dimension, but has one zero value in z5.

**Comment by constantinpape** [comment]
> Just another issue is that how I can save a variable that has no dimension, but has one zero value in z5.
> [](#)

I don't think zero dimensions are supported right now, but I am acually not quite sure about this.
In any case, you could store it as a 1D dataset of length 1.

**Comment by constantinpape** [comment]
The original issue is resolved, so I am closing this for now.
