### ISSUE TITLE
Different names?

### ISSUE THREAD

**Issue by gdkrmr** [constantinpape/z5#153]
https://github.com/constantinpape/z5/blob/c47e9acd08f24d7dd808f536a455216c7f627541/include/z5/types/types.hxx#L258

Why do these have different names?

**Comment by constantinpape** [comment]
> Why do these have different names?

For historic reasons:
initially, the metadata object did not have a member [`compressionOptions`](https://github.com/constantinpape/z5/blob/master/include/z5/metadata.hxx#L220) (which is a [`map<str, variant>`](https://github.com/constantinpape/z5/blob/master/include/z5/types/types.hxx#L215)), but it had different members called `codec`, `level` and `shuffle`, which needed to be set for each compressor (although they might have different or no meaning for different compression algorithms).

I changed to the new pattern at some point, which is more appropriate, but I still kept the old names.
There is actually no good reason for this, so I think that `"codec"` could just be renamed to `"cname"` which would make everything less confusing.

**Comment by gdkrmr** [comment]
are the values written to `.zarray` standardized?

**Comment by constantinpape** [comment]
Yes, they are. For blosc it's "cname", "clevel" and "shuffle". But z5 has different internal names for the historic reasons pointed out above.

**Comment by gdkrmr** [comment]
thanks for the clarifications!
