### ISSUE TITLE
Why is "lzf" the default blosc compression?

### ISSUE THREAD

**Issue by gdkrmr** [constantinpape/z5#154]
https://github.com/constantinpape/z5/blob/3eaa042b5a4cf47e437d1cfa4b64368d06aecd20/include/z5/types/types.hxx#L338

`"lzf"` is not mentioned in the blosc compression algorithms (https://github.com/Blosc/c-blosc/blob/7d0b2063f1f0864ba4d932a101ec0db2613786b4/blosc/blosc.h#L74).

**Comment by constantinpape** [comment]
Good catch! This is a typo and it should be `lz4`.

I guess this was not caught earlier because `z5` is mostly used from python, were the default value is correct, sorry about that.

Feel free to make a PR and fix it :).
