### ISSUE TITLE
api inconsistency with h5py when using pathlib.Path

### ISSUE THREAD

**Issue by k-dominik** [constantinpape/z5#160]
Currently (`h5py 2.9.0`) allows creating file handles using a `pathlib.Path`:

```python
import h5py
import pathlib

path = pathlib.Path("/tmp/file.h5")
file = h5py.File(path, "w")
```

the same in `z5py 2.0.3`:

```python
import z5py
import pathlib

path = pathlib.Path("/tmp/file.h5")
file = h5py.File(path, "w")
```
will result in

```pytb

~/miniconda3/envs/idev/lib/python3.7/site-packages/z5py/file.py in __init__(self, path, mode, use_zarr_format)
     65                 raise RuntimeError("Zarr file cannot be opened in N5 format")
     66 
---> 67         handle = _z5py.File(path, _z5py.FileMode(self.file_modes[mode]))
     68         mode = handle.mode()
     69 

TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. z5py._z5py.File(path: str, mode: z5::FileMode)

Invoked with: PosixPath('/tmp/tmpfile.h5'), <z5py._z5py.FileMode object at 0x7f6f007d2d88>
```

is this intended behavior, or do you plan to allow for the same api as with h5py?

**Comment by constantinpape** [comment]
> is this intended behavior, or do you plan to allow for the same api as with h5py?

This is not intended, it should work with `pathlib.Path` as well.
It should be enough to check if `isinstance(path, pathlib.Path)` and then get a string representation and pass it to the `_z5py.File`, which is a c++ function exposed via pybind and can only work with strings.

**Comment by emilmelnikov** [comment]
> > is this intended behavior, or do you plan to allow for the same api as with h5py?
> 
> This is not intended, it should work with `pathlib.Path` as well.
> It should be enough to check if `isinstance(path, pathlib.Path)` and then get a string representation and pass it to the `_z5py.File`, which is a c++ function exposed via pybind and can only work with strings.

One could also use more generic [`os.fspath`](https://docs.python.org/3/library/os.html#os.fspath).

**Comment by constantinpape** [comment]
> One could also use more generic [`os.fspath`](https://docs.python.org/3/library/os.html#os.fspath)

Yes, @clbarnes brought that up in #161 as well.
