### ISSUE TITLE
support blosc without (null) compression

### ISSUE THREAD

**Issue by gdkrmr** [constantinpape/z5#174]
Tests of zarr-R on MacOS are currently failing[1], at some point I get the following message:

```
Blosc has not been compiled with '(null)' compression support.  Please use one having it
```

[1] https://github.com/gdkrmr/zarr-R/runs/1455441863?check_suite_focus=true

**Comment by constantinpape** [comment]
This error is raised by blosc here:
https://github.com/Blosc/c-blosc/blob/790fac52990c73ebc217393879b49c7376607538/blosc/blosc.c#L688-L694.

I am not a blosc expert, but I think that blosc always needs a compressor, so what you are trying to do is invalid and should indeed fail. (As far as I can tell, there is no valid code path for no compressor here: https://github.com/Blosc/c-blosc/blob/790fac52990c73ebc217393879b49c7376607538/blosc/blosc.c#L652-L695).
