### ISSUE TITLE
Incompatibility between h5py and z5py WRT numpy

### ISSUE THREAD

**Issue by pgunn** [constantinpape/z5#179]
Hello,
Right now, it is possible to do an np.unique on an HDF5 data volume, while doing the same on an n5 file through this interface gives an index error.

Will be attaching two datasets (seg.h5 and seg.n5) that I believe are equivalent to demonstrate shortly. To illustrate:

```
>>> import h5py
>>> import numpy as np
>>> h5h = h5py.File('seg.h5')
>>> h5h['seg'].shape
(100, 100, 100)
>>> np.unique(h5h['seg'])
array([   0,   1,   2,   ....]
```

```
>>> import z5py
>>> import numpy as np
>>> z5h = z5py.File('seg.n5')
>>> z5h['seg'].shape
(100, 100, 100)
>>> np.unique(z5h['seg'])
Traceback (most recent call last):
  File "<__array_function__ internals>", line 6, in unique
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/numpy/lib/arraysetops.py", line 261, in unique
    ar = np.asanyarray(ar)
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/numpy/core/_asarray.py", line 138, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/z5py/dataset.py", line 346, in __getitem__
    roi_begin, shape, to_squeeze = self.index_to_roi(index)
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/z5py/dataset.py", line 335, in index_to_roi
    normalized, to_squeeze = normalize_slices(index, self.shape)
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/z5py/shape_utils.py", line 145, in normalize_slices
    normalized.append(int_to_start_stop(int(item), shape[d]))
  File "/Users/pgunn/anaconda3/envs/paintman/lib/python3.7/site-packages/z5py/shape_utils.py", line 38, in int_to_start_stop
    raise ValueError('Index ({}) out of range (0-{})'.format(i, size - 1))
ValueError: Index (100) out of range (0-99)
Abort trap: 6
```

**Comment by pgunn** [comment]
Please find attached sample files
[files.zip](https://github.com/constantinpape/z5/files/5984190/files.zip)

**Comment by constantinpape** [comment]
Yes, that makes sense. the h5py Dataset implements `__array__`, so its possible to call numpy functions on it:
https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py#L1001-L1013

It's straight-forward to implement this for the `z5py.Dataset` as well, but note that this will load the whole array into memory (which is the same behaviour as in h5py); so this is not very efficient for larger datasets.

**Comment by clbarnes** [comment]
The efficient, z5-y way to handle this would be to use [Dask](https://docs.dask.org/en/latest/array-api.html): create a dask array wrapping the z5py dataset with the same chunking scheme (or a multiple of it) and use the `unique` function on that.

**Comment by pgunn** [comment]
I don't know how much frontend-backend API punchthrough is possible; right now I'm hoping to have compatible APIs even if they're not as efficient as they might be; my intended use of N5 is primarily as glue between a custom database and a piece of third-party Java software that uses N5 (they're deprecating their HDF5 support, kind of). Reimplementing all the h5py/numpy glue would probably be a lot of work.

**Comment by constantinpape** [comment]
> Reimplementing all the h5py/numpy glue would probably be a lot of work.

Ok, adding the `__array__` method to `z5py.Dataset` should be trivial:

```python
def __array__(self):
    return self[...]
``` 

@pgunn do you want to make a PR with this, including a couple of tests for your use-case?

**Comment by pgunn** [comment]
I will try to put together a build environment. and see how it goes.

**Comment by pgunn** [comment]
I'm having trouble getting cmake to do test builds without it trying to write into /usr/local -- it looks to have some additional plumbing for installing additional cmake rules that I don't understand.

**Comment by constantinpape** [comment]
> it looks to have some additional plumbing for installing additional cmake rules that I don't understand.

You can change the install location via `CMAKE_INSTALL_PREFIX`, either by passing it via `-DCMAKE_INSTALL_PREFIX` or changing it with ccmake or cmake-gui.

**Comment by clbarnes** [comment]
I have generally just let CI deal with the test/ build environment, as working on the python side shouldn't affect the compilation at all.

**Comment by pgunn** [comment]
Thanks for the hint, @clbarnes  (also, good to see you again). I tried the CMAKE_INSTALL_PREFIX thing before reporting back (part of my very small bag of cmake tricks), but that's apparently not all the plumbing relating to paths ("make install" made it further but choked on installing cmake hintfiles or something). Hoping this PR passes tests and works.

**Comment by constantinpape** [comment]
> but that's apparently not all the plumbing relating to paths

Good point. There is also `Z5_CMAKECONFIG_INSTALL_DIR`, which is the location where the cmake config will be installed. It needs to be set to `${INSTALL_PREFIX}/lib/cmake/z5`.

I should update cmake so that it's automatically set to the correct path.

> Hoping this PR passes tests and works.

Yes, all passed and already merged :).
