### ISSUE TITLE
support python version higher than 3.7?

### ISSUE THREAD

**Issue by jingpengw** [constantinpape/z5#189]
Hi, thanks for making this package.
Python 3.7 is sort of outdated now. When I try to install this package in python 3.9, it says that it requires python 3.7. Does it make sense to lift the version requirement?

**Comment by constantinpape** [comment]
It's available for python 3.7, 3.8 and 3.9 on conda-forge: https://anaconda.org/conda-forge/z5py/files.
So there is no such restriction on the python version.

How are you trying to install it?

**Comment by jingpengw** [comment]
oh, sorry. 
Indeed, it is available.

**Comment by jakirkham** [comment]
Also a Python 3.10 migration in conda-forge is in progress
