### ISSUE TITLE
[question] Rational way to interface zarr with Rust

### ISSUE THREAD

**Issue by KestutisMa** [constantinpape/z5#201]
It's not real a z5py issue, but I think still interesting, as Rust probably could be useful in research (https://www.nature.com/articles/d41586-020-03382-2).

What could be good way to interface zarr with project in Rust?

- Maybe write small custom wrapper of z5 c++ using [rust c ffi](https://doc.rust-lang.org/nomicon/ffi.html)?
- Or use z5py with [pyo3.rs](https://pyo3.rs/latest/python_from_rust.html)?

Native rust zarr implementation seems unmaintained for 2 years https://github.com/sci-rs/zarr.
Also, seems there were [discussions](https://github.com/zarr-developers/community/issues/5), but last post was about a year ago and no working implementation yet.

**Comment by clbarnes** [comment]
The [rust N5 implementation](https://github.com/aschampion/rust-n5) is in (occasional) use and would certainly serve as a good base. As discussed in that issue, there are possibly design changes which could minimise allocations, but they haven't been forthcoming. Deep optimisation at that level seemed like an unnecessary optimisation when these formats are designed to suppose very heavy IO which would drastically outweigh any marginal gains on path-handling end.

We were resistant to putting significant effort into a rust implementation of zarr v2 when zarr v3 is "around the corner", but there hasn't been a lot of progress on that front in the last couple of years either.

A proposal rust implementation, potentially based off rust-n5, would certainly be welcome.

**Comment by KestutisMa** [comment]
Thank you! Good to know.
