### ISSUE TITLE
Version tag convention

### ISSUE THREAD

**Issue by stuarteberg** [constantinpape/z5#22]
This repo currently has three release tags: `0.01`, `0.02`, and `0.1`.

To a human, it's obvious that `0.1` > `0.02`.  But sadly, conda disagrees -- it's telling me that switching from `0.02.postXX` to `0.1.postXX` is a "downgrade".

I suggest deleting the `0.1` tag and replacing it with `0.10` to avoid confusion.

(FWIW, I had no idea that conda behaved this way.  Ulli wrote their version comparision code... I suppose he'd be the guy to ask if we really care to follow up on this.  But I'm not inclined to follow up.)

**Comment by stuarteberg** [comment]
Also: After you re-tag and re-build, you'll probably want delete the mis-versioned packages from [your channel](https://anaconda.org/cpape/z5py/files) to avoid confusion.

**Comment by constantinpape** [comment]
Thanks for the heads up.
I am working on the new release and will take this into account.

**Comment by constantinpape** [comment]
I released 0.2 and removed the 0.01 and 0.02 tags and packages.
I will upload a 0.2 package to my anaconda channel later,
then all version confusion should be fixed.
