### ISSUE TITLE
Dropping Boost in favor of std==C++17?

### ISSUE THREAD

**Issue by sameeul** [constantinpape/z5#223]
Now that C++17 is supported by all the major compilers, just checking if you are thinking about dropping boost all-together use `std::filesystem` and `std::variant` from C++17? I took a look at the current usage of `boost` in the codebase and feel that it can be dropped if we switch to C++17.

Any thoughts on that? I can start working on it if you think it might be a good direction.

**Comment by constantinpape** [comment]
> Any thoughts on that? I can start working on it if you think it might be a good direction.

Yes, that is a good idea!

A contribution on this would be welcome!
