### ISSUE TITLE
boost missing in conda install

### ISSUE THREAD

**Issue by clbarnes** [constantinpape/z5#37]
Steps to reproduce:

```bash
conda create -n new-env python=2.7
source activate new-env
conda install -c cpape z5py
python -c "import z5py"
```

Output:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cbarnes/.pyenv/versions/gp2c/lib/python2.7/site-packages/z5py/__init__.py", line 1, in <module>
    from .file import File
  File "/home/cbarnes/.pyenv/versions/gp2c/lib/python2.7/site-packages/z5py/file.py", line 2, in <module>
    from .base import Base
  File "/home/cbarnes/.pyenv/versions/gp2c/lib/python2.7/site-packages/z5py/base.py", line 3, in <module>
    from .dataset import Dataset
  File "/home/cbarnes/.pyenv/versions/gp2c/lib/python2.7/site-packages/z5py/dataset.py", line 6, in <module>
    from ._z5py import DatasetImpl, open_dataset
ImportError: libboost_filesystem.so.1.66.0: cannot open shared object file: No such file or directory
```

Happens on my local machine and on travis with downstream packages: https://travis-ci.org/clbarnes/gunpowder/builds/352954671 (build is green, but the 4 skipped tests are tests which tried to import z5py and failed)

**Comment by constantinpape** [comment]
Which boost version is installed in your environment?
Do you have conda-forge as higher priority channel than anaconda in your `.condarc` ?
If not, `conda install -c cpape -c conda-forge z5py` might fix the issue.

**Comment by clbarnes** [comment]
Good point; by default, it seems to pull in libboost 1.65, which would explain the missing 1.66.0

Repo with a trivial failing case here: https://github.com/clbarnes/z5_boost_bug and build here https://travis-ci.org/clbarnes/z5_boost_bug/jobs/352965504

I'll kick off another build with that fix to test it.

**Comment by constantinpape** [comment]
I don't get why it would pull 1.65. It should be fixed to 1.66.0 here:
https://github.com/constantinpape/z5/blob/master/conda-recipe/meta.yaml#L33

**Comment by clbarnes** [comment]
Maybe the default channel doesn't have 1.66 and conda just throws its arms up and uses the old one.

Successful build with the conda-forge channel added here https://travis-ci.org/clbarnes/z5_boost_bug/builds/352968043 (the 3.4 build is doing something weird, picking up 3.6 libraries, so I'd just ignore that).

My fault for not including the conda-forge channel, sorry!

**Comment by constantinpape** [comment]
Glad I could help.
