### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#41]
Some issues with the current version have emerged and for fixing them changing the (python) API
might be in order. This implies bumping the major version number to make a release 1.0.
Here is a list of issues that should (potentially) be fixed for that release:

- Compatability with `h5py`: This requires creating a dataset with data and making chunks, as well as
datatype optional, see #30. Also implies having proper file permissions, see #28.
- Consistent error handling: Throw same exceptions for permissions as h5py and remove AssertionErrors, see #36.
- Speed up performance for N >= 4, see #19.
-  Don't write out empty chunks, see #39.
- Implement Java benchmarks, see #40.
- Enable creating nested names, see #53.

**Comment by constantinpape** [comment]
Once the release is there, the package should go to conda-forge, see #42.

**Comment by clbarnes** [comment]
It may be easier to organise these using a milestone https://help.github.com/articles/about-milestones/

**Comment by constantinpape** [comment]
Done: https://github.com/constantinpape/z5/milestone/1
