### ISSUE TITLE
Upload to conda-forge recipe

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#42]
Once release 1.0 #41 is there, the package should be submitted to conda-forge by making a PR to
https://github.com/conda-forge/feedstocks/tree/master/feedstocks.
While on it, windows builds would be nice to have too.

**Comment by jakirkham** [comment]
Please let me know if you need help going though this. Docs for adding a new recipe are [here]( https://conda-forge.org/#add_recipe ).

**Comment by constantinpape** [comment]
@jakirkham thanks for the offer.
Before preparing the conda-forge uploads, I wanted to check builds on Mac and Windows and I
have just gotten access to two Mac and Windows machines this week.
Once I have gone through the builds, I might pick you up on the offer ;).

**Comment by alimanfoo** [comment]
FWIW appveyor is a very nice CI service for automating build and test runs
on Windows.

**Comment by clbarnes** [comment]
Automating builds on 3 systems instead of 1 means this might also be a good time to look into factoring the build process out into a separate script, including adding dependencies to a `requirements.txt` - that would make local builds for developers more tractable as well.

**Comment by constantinpape** [comment]
I looked into getting a channel on conda-forge in the last days, see
https://github.com/conda-forge/staged-recipes/pull/6427

However, I hit a few roadblocks:
The major one: the conda-forge linux docker image uses GCC 4.8.2. which
does not support c++ 14 yet, and hence won't build with xtensor, which needs it.
I currently don't see how to overcome this.

@jakirkham Do you have any experience with similar issues?
Maybe we could at least use `conda-forge` for Windows and Mac, where the compilers do
support c++14. (Still having some build issues there too, but this should not be as serious)

**Comment by jakirkham** [comment]
Thanks for working on this. Added some review comments that should hopefully help. Please feel free to ask questions.

As to Linux, added a workaround in [this comment]( https://github.com/conda-forge/staged-recipes/pull/6427#issuecomment-411521907 ), which should give us GCC 7.2.0. Basically we are just taking an early adoption path to compilers that conda-forge will start using more broadly in the future. As Anaconda already uses them to build their whole stack, they should be quite stable. If you have trouble getting that to work, please let me know.

Looked at the other build issues. Think it is basically some of conda-forge's matrix build automation getting confused about recipe format. So once we deal with those issues expect those current problems will clear.

**Comment by constantinpape** [comment]
@jakirkham 
Thanks a lot for the comments on the recipe PR.
I just had a quick look, but most of it makes sense to me.
I will go through it tomorrow and try to incorporate the comments or 
ask if something is unclear.

**Comment by constantinpape** [comment]
Done!
z5py is on conda-forge.
