### ISSUE TITLE
GLIBCXX-based failures in downstream packages

### ISSUE THREAD

**Issue by clbarnes** [constantinpape/z5#43]
On my local machine it's fine, but on travis, downstream packages fail to import anything from `z5py`

https://travis-ci.org/funkey/gunpowder/builds/353384601#L890

https://github.com/clbarnes/gunpowder/blob/ceda3fd0923656aa1de81d6f7f2fe260b04fc809/.travis.yml

```
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/travis/miniconda/envs/gp-env/lib/python2.7/site-packages/z5py/_z5py.so)
```

This issue is documented here https://github.com/ContinuumIO/anaconda-issues/issues/483 , and the author of https://github.com/ContinuumIO/anaconda-issues/issues/483#issuecomment-149262721 is, fortunately, just downstairs.

**Comment by constantinpape** [comment]
Yes this is an issue with the old ABI version of libstd.
I actually thought that this:
https://github.com/constantinpape/z5/blob/master/CMakeLists.txt#L32
should fix the issue.
But apparently it doesn't.

Note that Stuart's comment is, afaik, not best practice any more.
In any case, for `z5py` it is not possible to use the default conda compiler (gcc 4.8.5) because
it does not support C++ 14.

Note that my travis build is working:
https://github.com/constantinpape/z5/blob/master/.travis.yml

I guess because I am pulling in gcc 6:
https://github.com/constantinpape/z5/blob/master/.travis.yml#L26

**Comment by constantinpape** [comment]
Maybe you could also use this as a work-around?
I can look into fixing the ABI issues, but I don't think I will have time for this today or tomorrow.

**Comment by clbarnes** [comment]
Is it possible for conda to pull in the newer gcc as a run dependency in the downstream environment? Or is it that it needs other packages in the environment to have been built with that GCC too?

**Comment by constantinpape** [comment]
@clbarnes 
Do you still have this issue or have you found a workaround ?

**Comment by clbarnes** [comment]
This seems to only affect python 3.4 (2.7 and 3.5+ are fine)

Ignore the title of the repo - https://travis-ci.org/clbarnes/z5_boost_bug/builds/352968043

If the 3.3 lifecycle is anything to go on, the problem may resolve itself in a few months when 3.4 goes EOL. I tried installing gcc-6 as you did but the install failed https://travis-ci.org/clbarnes/z5_boost_bug

I'm fine to leave this issue as a wontfix for documentation purposes until py3.4 EOL.

**Comment by clbarnes** [comment]
Actually, scratch that. This behaviour is weird. In the test repo clbarnes/z5_boost_bug , only py3.4 fails. However, in the gunpowder repo, py2.7 fails (with the same message as the test repo does with 3.4, when py2.7 passes). Maybe it's related to the gunpowder repo using a mixture of conda and pip? But that shouldn't affect the existence of compiled libraries, especially as the z5py installation is done before the pip stuff.

**Comment by constantinpape** [comment]
Can you just change to the gcc conda 5.4 version to fix this?

I thought that sticking to the old libstd ABI should fix these issues:
https://github.com/constantinpape/z5/blob/master/CMakeLists.txt#L32
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

But apparently this is not the case...
If this keeps being an issue, I could try going through
https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html
to find a solution that makes it work with older libstd versions.

**Comment by constantinpape** [comment]
Ok, closing this for now.
Feel free to reopen if the issue pops up again.
