### ISSUE TITLE
Windows issues

### ISSUE THREAD

**Issue by constantinpape** [constantinpape/z5#72]
The appveyor windows test fail, because the `boost::filesystem::path` constructor fails with `std::length_error: string too long`. See:
https://ci.appveyor.com/project/constantinpape/z5/build/1.0.116

The only related issues I could find online suggest that this issue is related to linking against incorrect boost libraries:
https://stackoverflow.com/questions/8552909/boost-filesystempath-constructor-stdlength-error
https://stackoverflow.com/questions/22356045/boost-filesystem-suprious-errors-temp-directory-path-returns-bad-ptr/22358339

I have tried a few different boost options here:
https://github.com/constantinpape/z5/blob/fix-win-tests/CMakeLists.txt#L117
But so far nothing has helped. See also:
https://cmake.org/cmake/help/v3.0/module/FindBoost.html

**Comment by constantinpape** [comment]
Note that this is not an issue in the conda-forge packages, so seems to be some weirdness in my appveyor config.

**Comment by jakirkham** [comment]
Does it happen with Visual Studio 2015?

**Comment by constantinpape** [comment]
No, I only use 2017 (64bit), see
https://github.com/constantinpape/z5/blob/master/appveyor.yml#L8

**Comment by jakirkham** [comment]
Right. conda-forge uses 2015. So am wondering if that’s part of the problem.

**Comment by constantinpape** [comment]
I activated 2015 in the last commit, build is still failing:
https://ci.appveyor.com/project/constantinpape/z5/build/1.0.136
I have only tested 64 bit though (what are conda-forge builds?).
Gonna try 32 bit now.

**Comment by constantinpape** [comment]
Fixed by #124.
