### ISSUE TITLE
support leading slashes for internal paths

### ISSUE THREAD

**Issue by k-dominik** [constantinpape/z5#73]
Heya, thanks for this wonderful library.

It would be cool if leading slashes for dataset names could be supported, as they are in `h5py`.

So stuff like `...create_dataset('/blah' ...)`

**Comment by constantinpape** [comment]
ec796c952173db23879 fixes the issue for `__getitem__`.

**Comment by constantinpape** [comment]
4b5d22e0254f7f2d7612dd376c78bbc34ddcd094 should fix the rest
