### ISSUE TITLE
Attribute serialization fails for anything that is not json serializable

### ISSUE THREAD

**Issue by k-dominik** [constantinpape/z5#74]
When adding custom attributes to datasets, things will fail if they are not types that can be serialized by pythons `json` module.
It would be cool if one could supply an custom serializer (stuff derived from `JSONEncoder`...)

**Comment by constantinpape** [comment]
I have implemented a fix in #75.
Not sure if the solution I chose is optimal.
You can set the `Encoder` / `Decoder` to be used globally via 
`z5py.set_json_encoder` / `z5py.set_json_decoder`. 
It must inherit from `JSONEncoder` / `JSONDecoder` or be `None` (which resets to the default impl).

@k-dominik  let me know what you think.

**Comment by constantinpape** [comment]
Merged into master, so closing the issue.
Use https://github.com/constantinpape/z5/blob/master/src/python/module/z5py/attribute_manager.py#L22
to set the encoder. Similar for decoder.
