### ISSUE TITLE
default compression behavior

### ISSUE THREAD

**Issue by k-dominik** [constantinpape/z5#88]
The current implementation uses a default compression for data if compression is not specified explicitly:

https://github.com/constantinpape/z5/blob/0766a1e814b1f7e4e6d1d9d8ac637446ada53d23/src/python/module/z5py/dataset.py#L293-L294

and

https://github.com/constantinpape/z5/blob/0766a1e814b1f7e4e6d1d9d8ac637446ada53d23/src/python/module/z5py/dataset.py#L56

I don't want to say that this is a real problem, but it sure breaks compatibility of the api with `h5`. As it looks to be on purpose, one should at least document this.

**Comment by clbarnes** [comment]
Yes: the rationale is that the N5/zarr formats mainly become valuable over HDF5 with large data, and therefore that compressed was a more convenient default. It should be specified in the README, though.
