### ISSUE TITLE
z5py.File fails when parent directory does not exist

### ISSUE THREAD

**Issue by hanslovsky** [constantinpape/z5#95]
This works:
```sh
 △ ~ TMP_N5_DIR=`mktemp -d` && python -c "import z5py; import os; f = z5py.File(os.path.join('$TMP_N5_DIR', 'container.n5'))"
```

This fails:
```sh
 ▲ ~ TMP_N5_DIR=`mktemp -d` && python -c "import z5py; import os; f = z5py.File(os.path.join('$TMP_N5_DIR', 'some', 'container.n5'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/hanslovskyp/miniconda3/envs/z5py-test/lib/python3.6/site-packages/z5py/file.py", line 93, in __init__
    os.mkdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp.m6d9reAMkd/some/container.n5'
```

If the desired behavior is to create all parent directories (and I think it should be), [`os.mkdir(path)`](https://github.com/constantinpape/z5/blob/0e19980daff4706d27e9c36f4ad964ffe1ec4d82/src/python/module/z5py/file.py#L93) could be replaced with [`os.makedirs(path, exist_ok=True)`](https://docs.python.org/3/library/os.html#os.makedirs). It is probably even better to first `try` creating the directory then put the [logic for existing containers](https://github.com/constantinpape/z5/blob/0e19980daff4706d27e9c36f4ad964ffe1ec4d82/src/python/module/z5py/file.py#L75-L87) in the `except` clause of [`OSError`](https://docs.python.org/3/library/exceptions.html#OSError) with an appropriate `errno`

Conda environment:
```
# packages in environment at /home/hanslovskyp/miniconda3/envs/z5py-test:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
blosc                     1.15.1            hf484d3e_1002    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
intel-openmp              2019.1                      144  
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h470a237_1    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
openssl                   1.0.2p            h14c3975_1002    conda-forge
pip                       18.1                  py36_1000    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
z5py                      1.4.0           py36h9082789_1000    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by constantinpape** [comment]
I tried to keep the API as close to `h5py` as possible and in this case it behaves in the same way, also raising an `OSError` if the parent directory does not exist.
I also think that this is reasonable behavior, because often the fact that the parent directory does not exist is due to a typo rather then something intended by the user.
Adding an additional `os.makedirs` for the parent dir also doesn't add much complexity on the user side if this behavior is intended.
Do you think I am missing any good reasons to support this aside minor convenience?

**Comment by hanslovsky** [comment]
> I tried to keep the API as close to `h5py` as possible and in this case it behaves in the same way, also raising an `OSError` if the parent directory does not exist.

This is an understandable decision. Java N5 [creates all (parent) directories](https://github.com/saalfeldlab/n5/blob/3fb8876c83765b0cd499bf99cd9851817ef26107/src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java#L73).

I personally find the convenience preferable over conforming with `h5py` but that is not my decision to make.

**Comment by constantinpape** [comment]
> This is an understandable decision. Java N5 [creates all (parent) directories](https://github.com/saalfeldlab/n5/blob/3fb8876c83765b0cd499bf99cd9851817ef26107/src/main/java/org/janelia/saalfeldlab/n5/N5FSWriter.java#L73).

Ok, I see why you expected this behavior here then.

Anyway, I will close this for now. I don't see the minor convenience worth departing from `h5py` API here.
